# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build srs`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t srs`.
FROM docker.io/node:lts as build
RUN npm install -g node-gyp

WORKDIR /build
COPY . .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN yarn install
RUN yarn nx run-many -t build

FROM docker.io/node:lts
COPY --from=build /build/dist/apps/srs /app
COPY --from=build /build/dist/apps/frontend /app/public
WORKDIR /app

RUN yarn install
RUN npx playwright install chromium
RUN npx playwright install-deps

CMD [ "node", "/app/main.js" ]
