version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    container_name: srs-app
    build:
      context: .
      dockerfile: Dockerfile
    image: srs-app
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      RUN_MODE: scrape
      HOST: 0.0.0.0
      PORT: 8080
    links:
      - db
    volumes:
      - './:/src'
volumes:
  postgres_db:
    driver: local
